server:
  port: 8000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/local
    tomcat:
      initial-size: 20
      max-active: 20
  redis:
    host: localhost
    port: 6379
logging:
  level:
    root: info
mybatis:
  mapper-locations: classpath:mapperxml/*.xml